
version: 2

sources:
  - name: mysql_sakila
    database: sakila_raw
    schema: mysql_rds_sakila
    tables:
      - name: actor
      - name: address
      - name: category
      - name: city
      - name: country
      - name: customer
      - name: film
      - name: film_actor
      - name: film_category
      - name: film_text
      - name: fivetran_audit
      - name: inventory
      - name: language
      - name: payment
      - name: rental
      - name: staff
      - name: store



